name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        redmica_branch: [master, released-latest]
        db: [postgres, mysql, sqlite]
    runs-on: ubuntu-latest
    container:
      image: redmica/redmica:latest
      env:
        RAILS_ENV: test
      ports:
        - 3000:3000
    services:
      chrome:
        image: selenium/standalone-chrome-debug:3.141.59-europium
        ports:
          - 4444:4444
          - 5900:5900
      if: matrix.db == 'postgres' || matrix.db == 'mysql'
      postgres_host:
        image: postgres:11
        env:
          LANG: C.UTF-8
          POSTGRES_INITDB_ARGS: --locale=C.UTF-8
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      mysql_host:
        image: mysql:5
        env:
          MYSQL_ROOT_PASSWORD: password
        ports:
          - 3306:3306
    defaults:
      run:
        working-directory: /usr/src/redmine
    steps:
      - uses: actions/checkout@v2
      - name: Setup
        run: /usr/src/redmine/plugins/redmica_ui_extension/setup-redmica.sh ${{matrix.redmica_branch}} mysql
      - name: Test RedMica UI Extension plugin
        run: RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
      - name: Test RedMica
        run: RAILS_ENV=test bundle exec rake test