name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test-with-postgres:
    strategy:
      fail-fast: false
      matrix:
        redmica: [master, released-latest]
    runs-on: ubuntu-latest
    container:
      image: redmica/redmica:latest
      env:
        RAILS_ENV: test
      ports:
        - 3000:3000
    services:
      chrome:
        image: selenium/standalone-chrome-debug:3.141.59-europium
        ports:
          - 4444:4444
          - 5900:5900
    defaults:
      run:
        working-directory: /usr/src/redmine
    steps:
      - uses: actions/checkout@v2
      - name: Replace RedMica directory
        if: matrix.redmica == 'master'
        run: |
          set +e
          rm -rf /usr/src/redmine/* > /dev/null
          rm -rf /usr/src/redmine/.* 2> /dev/null
          set -e
          wget --no-check-certificate wget --no-check-certificate https://github.com/redmica/redmica/archive/master.tar.gz;
          tar -xf master.tar.gz --strip-components=1;
      - name: Move repository directory
        run: cp -r /__w/redmica_ui_extension/redmica_ui_extension /usr/src/redmine/plugins
      - name: Setup
        run: |
          cp /usr/src/redmine/plugins/redmica_ui_extension/.github/templates/database.yml /usr/src/redmine/config/database.yml
          cp /usr/src/redmine/plugins/redmica_ui_extension/.github/templates/application_system_test_case.rb /usr/src/redmine/test/application_system_test_case.rb
          # PDFのサムネイル作成テストを成功させるため
          sed -i 's/^.*policy.*coder.*none.*PDF.*//' /etc/ImageMagick-6/policy.xml
          # DB側のログを表示しないため
          rm /usr/src/redmine/config/additional_environment.rb
          apt update
          apt install -y build-essential
          bundle install --with test
          bundle update
          bundle exec rake db:create db:migrate RAILS_ENV=test
      - name: Test RedMica UI Extension plugin
        run: RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
      - name: Test RedMica
        run: RAILS_ENV=test bundle exec rake test