name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test-with-postgres:
    strategy:
      fail-fast: false
      matrix:
        redmica: [1.2]
    runs-on: ubuntu-latest
    container:
      image: redmica/redmica:${{ matrix.redmica }}
    defaults:
      run:
        working-directory: /usr/src/redmine
    steps:
      - name: check
        run: pwd; ls /usr/src/redmine
      - uses: actions/checkout@v2
      - name: Move repository directory
        run: cp -r /__w/redmica_ui_extension/redmica_ui_extension /usr/src/redmine/plugins; ls /usr/src/redmine/plugins/redmica_ui_extension
      - name: Setup
        run: bundle install
      - name: Test RedMica
        run: RAILS_ENV=test bundle exec rake test
      - name: Test RedMica UI Extension plugin
        run: RAILS_ENV=test bundle exec rake test TEST=plugins/redmica_ui_extension/test
